# Generated by Django 3.2.6 on 2021-08-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedbook',
            old_name='requested',
            new_name='requested_user',
        ),
        migrations.AddField(
            model_name='book',
            name='available_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
