# Generated by Django 3.2.6 on 2021-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_now',
            field=models.BooleanField(default=False),
        ),
    ]
